DROP TABLE REPLY;
DROP TABLE BOARD;
DROP TABLE MEMBER;

DROP SEQUENCE SEQ_UNO;
DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_RNO;

--------------------------------------------------
--------------     MEMBER 관련	------------------	
--------------------------------------------------

CREATE TABLE MEMBER (
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(30) NOT NULL UNIQUE,
  USER_PWD VARCHAR2(100) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL,
  EMAIL VARCHAR2(100),
  BIRTHDAY DATE,
  GENDER VARCHAR2(1) CHECK (GENDER IN('M', 'F')),
  PHONE VARCHAR2(13),
  ADDRESS VARCHAR2(100),
  ENROLL_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

CREATE SEQUENCE SEQ_UNO NOCACHE;

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', '관리자', 'admin@kh.or.kr', '800918', 'F', '010-1111-2222', '서울시 강남구 역삼동', '20180101', '20180101', DEFAULT);

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user01', 'pass01', '홍길동', 'user01@kh.or.kr', '900213', 'M','010-3333-4444', '서울시 양천구 목동', '20180201', '20180202', DEFAULT);

COMMIT;



----------------------------------------------------
-----------------     BOARD 관련        ------------------	
----------------------------------------------------

CREATE TABLE BOARD(
  BOARD_NO NUMBER PRIMARY KEY,
  BOARD_TITLE VARCHAR2(100) NOT NULL,
  BOARD_CONTENT VARCHAR2(4000) NOT NULL,
  BOARD_WRITER NUMBER,
  COUNT NUMBER DEFAULT 0,
  CREATE_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
  FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER
);

CREATE SEQUENCE SEQ_BNO NOCACHE;

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '첫번째 게시판 서비스를 시작하겠습니다.', '안녕하세요. 첫 게시판입니다.', 1, DEFAULT, '20180210', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '두번째 게시판 서비스를 시작하겠습니다.', '안녕하세요. 2 게시판입니다.', 2, DEFAULT, '20180211', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '하이 에브리원 게시판 서비스를 시작하겠습니다.', '안녕하세요. 3 게시판입니다.', 1, DEFAULT, '20180212', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '안녕.. 마이바티스는 처음이지?', '안녕하세요. 첫 게시판입니다.', 2, DEFAULT, '20180220', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '어서와 ㅎㅎㅎㅎ', '반갑습니다.', 1, DEFAULT, '20180220', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '페이징 처리때문에 샘플데이터 많이 넣어놓는다...', '안녕하십니까', 2, DEFAULT, '20180221', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '게시판 서비스', '안녕하세요. 게시판입니다.', 1, DEFAULT, '20180221', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '샘플데이터들 ', '안녕하세요.', 2, DEFAULT, '20180224', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '모두들 화이팅!!', '화이팅 하세요!!', 1, DEFAULT, '20180301', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '힘내세요!!!', ' 게시판입니다.', 1, DEFAULT, '20180301', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '게시판 서비스', '프레임워크는 처음이지?', 1, DEFAULT, '20180301', DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '시작하겠습니다.', '지금부터 시작!!', 2, DEFAULT, '20181021',DEFAULT);

INSERT INTO BOARD 
VALUES(SEQ_BNO.NEXTVAL, '마지막 게시판 시작하겠습니다.', '안녕하세요. 마지막 게시판입니다.', 1, DEFAULT, '20181021', DEFAULT);



----------------------------------------------------
----------------    REPLY 관련         -------------------	
----------------------------------------------------

CREATE TABLE REPLY(
  REPLY_NO NUMBER PRIMARY KEY,
  REPLY_CONTENT VARCHAR2(400),
  REF_BNO NUMBER,
  REPLY_WRITER NUMBER,
  CREATE_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (REF_BNO) REFERENCES BOARD,
  FOREIGN KEY (REPLY_WRITER) REFERENCES MEMBER
);

CREATE SEQUENCE SEQ_RNO;

INSERT INTO REPLY
VALUES(SEQ_RNO.NEXTVAL, '첫번째 댓글입니다.', 1,  2, '20230315', DEFAULT);

INSERT INTO REPLY
VALUES(SEQ_RNO.NEXTVAL, '첫번째 댓글입니다.', 13, 2, '20230314', DEFAULT);

INSERT INTO REPLY
VALUES(SEQ_RNO.NEXTVAL, '두번째 댓글입니다.', 13, 2, '20230313', DEFAULT);

INSERT INTO REPLY
VALUES(SEQ_RNO.NEXTVAL, '마지막 댓글입니다.', 13, 2, '20230312', DEFAULT);



COMMIT;